const config = require('../../config');
const axios = require('axios');

module.exports = {
    name: 'imagine',
    aliases: ['genimg', 'imgen', 'draw'],
    category: 'ai',
    description: 'Generate an image from text',
    weight: 'heavy'
    usage: `${config.prefix}imagine <prompt>`,
    
    async execute(sock, msg, args) {
        try {
            const jid = msg.key.remoteJid;
            if (!args[0]) return await sock.sendMessage(jid, { text: `❌ Usage: ${this.usage}` });
            
            const prompt = args.join(' ');
            const wait = await sock.sendMessage(jid, { text: '🎨 Generating image...' });
            
            // Using Pollinations.ai (free, no key needed)
            const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&nologo=true`;
            
            await sock.sendMessage(jid, { delete: wait.key });
            
            await sock.sendMessage(jid, {
                image: { url: imageUrl },
                caption: `🎨 *Prompt:* ${prompt}\n\n> Generated by VANTAGE-X MD`
            });
        } catch (error) {
            console.error('Imagine error:', error.message);
            await sock.sendMessage(msg.key.remoteJid, { text: global.mess.error });
        }
    }
};